### ISSUE TITLE
Import errors while starting

### ISSUE THREAD

**Issue by mlieshoff** [Vaskivo/DungeonCrawler-tile-maker#1]
Hey, i tried out your tile maker, but cannot start it... Do you have a clue or a fix for it? I tried also with Python 2 and 3.7, same results.

```$ python3 --version
Python 3.3.7
$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name _imaging
```

Thanks in advance :)

**Comment by mlieshoff** [comment]
Issue fixed with using python virtual env:

``
> sudo apt-get install python3-venv
> python3 -m venv test_env
> source test_env/bin/activate
> (test_env) python --version
< (test_env) Python 3.8.5
> (test_env) pip install Pillow
> (test_env) pip install numpy
> (test_env) python main.py

Great job man with the tile maker, i really like it! Maybe the instruction for the virtual env could be added to the readme file.
